#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Template-Plugin-HTML-Prototype
version:      0.01
version_from: lib/Template/Plugin/HTML/Prototype.pm
installdirs:  site
requires:
    Template:                      0
    HTML::Prototype:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
